using System.Globalization;
using System.Text;

namespace AICodingServices.Data.Tests;

public sealed class SyntheticEditWorkflowTokenBenchmarkTests
{
    [Fact]
    [Trait("Suite", "TokenBenchmark")]
    public void Synthetic_large_file_edit_context_baseline()
    {
        string repositoryRoot = ResolveRepositoryRoot();
        string sourcePath = Path.Combine(repositoryRoot, "src", "AICodingServices.McpServer", "Program.cs");
        Assert.True(File.Exists(sourcePath), "Expected CodingServices MCP server Program.cs to exist for the synthetic benchmark.");

        string outputRoot = Environment.GetEnvironmentVariable("SYNTHETIC_EDIT_BENCH_OUT")
            ?? Path.Combine(repositoryRoot, "runtime", "token-benchmark", "synthetic-edit");
        Directory.CreateDirectory(outputRoot);

        string original = File.ReadAllText(sourcePath);
        string synthetic = CreateSyntheticLargeFile(original);
        string syntheticPath = Path.Combine(outputRoot, "SyntheticAICodingServicesMcpServer.cs");
        File.WriteAllText(syntheticPath, synthetic);

        SyntheticEdit[] edits = CreateEdits();
        List<MeasurementRow> rows = [];
        string current = synthetic;
        long manualTotalBytes = 0;
        long preciseToolTotalBytes = EstimateNewFilePayloadBytes(syntheticPath, synthetic);
        long wholeFileToolTotalBytes = EstimateSubmitFilePayloadBytes(syntheticPath, synthetic);

        for (int index = 0; index < edits.Length; index++)
        {
            SyntheticEdit edit = edits[index];
            Assert.Contains(edit.OldText, current, StringComparison.Ordinal);

            long fullReadBytes = CountUtf8(current);
            long precisePayloadBytes = EstimateReplaceTextPayloadBytes(syntheticPath, edit);
            string next = current.Replace(edit.OldText, edit.NewText, StringComparison.Ordinal);
            long wholeFilePayloadBytes = EstimateSubmitFilePayloadBytes(syntheticPath, next);

            manualTotalBytes += fullReadBytes + CountUtf8(edit.OldText) + CountUtf8(edit.NewText);
            preciseToolTotalBytes += precisePayloadBytes;
            wholeFileToolTotalBytes += wholeFilePayloadBytes;

            rows.Add(new MeasurementRow(
                index + 1,
                edit.Name,
                fullReadBytes,
                precisePayloadBytes,
                wholeFilePayloadBytes,
                manualTotalBytes,
                preciseToolTotalBytes,
                wholeFileToolTotalBytes));

            current = next;
        }

        string csvPath = Path.Combine(outputRoot, "synthetic-edit-measurements.csv");
        string summaryPath = Path.Combine(outputRoot, "synthetic-edit-summary.md");
        File.WriteAllText(csvPath, BuildCsv(rows));
        File.WriteAllText(summaryPath, BuildSummary(sourcePath, syntheticPath, rows, manualTotalBytes, preciseToolTotalBytes, wholeFileToolTotalBytes));

        Console.WriteLine(File.ReadAllText(summaryPath));
        Assert.True(preciseToolTotalBytes < manualTotalBytes, "Precise MCP-style text edits should use less context than repeated full-file manual reads.");
        Assert.True(wholeFileToolTotalBytes > preciseToolTotalBytes, "Whole-file submit_file edits should be more expensive than precise MCP-style text edits.");
    }

    private static SyntheticEdit[] CreateEdits()
    {
        return
        [
            new SyntheticEdit(
                "add-runtime-state-field",
                "    private readonly AICodingServicesMcpRuntimeState runtimeState;",
                "    private readonly AICodingServicesMcpRuntimeState runtimeState;\n    private readonly string syntheticBenchmarkRunId = \"synthetic-edit-baseline\";"),
            new SyntheticEdit(
                "rename-refresh-result-record",
                "public sealed record AICodingServicesRefreshIndexResult(",
                "public sealed record SyntheticAICodingServicesRefreshIndexResult("),
            new SyntheticEdit(
                "add-session-plan-reason-default",
                "    string Role,\n    string Reason);",
                "    string Role,\n    string Reason,\n    string SyntheticBenchmarkNote = \"precise-edit\");")
        ];
    }

    private static string CreateSyntheticLargeFile(string original)
    {
        string synthetic = original
            .Replace("namespace AICodingServices.McpServer;", "namespace AICodingServices.SyntheticTokenBench;", StringComparison.Ordinal)
            .Replace("AICodingServicesTools", "SyntheticAICodingServicesTools", StringComparison.Ordinal)
            .Replace("AICodingServicesMcpStatus", "SyntheticAICodingServicesMcpStatus", StringComparison.Ordinal);

        return "// Synthetic benchmark duplicate. Generated by SyntheticEditWorkflowTokenBenchmarkTests.\n"
            + "// This file intentionally lives under runtime output and is not product source.\n"
            + synthetic;
    }

    private static long EstimateNewFilePayloadBytes(string path, string content)
    {
        return CountUtf8(path) + CountUtf8(content) + 256;
    }

    private static long EstimateSubmitFilePayloadBytes(string path, string content)
    {
        return CountUtf8(path) + CountUtf8(content) + 256;
    }

    private static long EstimateReplaceTextPayloadBytes(string path, SyntheticEdit edit)
    {
        return CountUtf8(path) + CountUtf8(edit.OldText) + CountUtf8(edit.NewText) + 512;
    }

    private static string BuildCsv(IReadOnlyList<MeasurementRow> rows)
    {
        StringBuilder builder = new();
        builder.AppendLine("step,name,manualFullReadBytes,preciseToolPayloadBytes,wholeFileToolPayloadBytes,cumulativeManualBytes,cumulativePreciseToolBytes,cumulativeWholeFileToolBytes");
        foreach (MeasurementRow row in rows)
        {
            builder
                .Append(row.Step.ToString(CultureInfo.InvariantCulture)).Append(',')
                .Append(EscapeCsv(row.Name)).Append(',')
                .Append(row.ManualFullReadBytes.ToString(CultureInfo.InvariantCulture)).Append(',')
                .Append(row.PreciseToolPayloadBytes.ToString(CultureInfo.InvariantCulture)).Append(',')
                .Append(row.WholeFileToolPayloadBytes.ToString(CultureInfo.InvariantCulture)).Append(',')
                .Append(row.CumulativeManualBytes.ToString(CultureInfo.InvariantCulture)).Append(',')
                .Append(row.CumulativePreciseToolBytes.ToString(CultureInfo.InvariantCulture)).Append(',')
                .Append(row.CumulativeWholeFileToolBytes.ToString(CultureInfo.InvariantCulture))
                .AppendLine();
        }

        return builder.ToString();
    }

    private static string BuildSummary(
        string sourcePath,
        string syntheticPath,
        IReadOnlyList<MeasurementRow> rows,
        long manualTotalBytes,
        long preciseToolTotalBytes,
        long wholeFileToolTotalBytes)
    {
        double manualTokens = EstimateTokens(manualTotalBytes);
        double preciseTokens = EstimateTokens(preciseToolTotalBytes);
        double wholeFileTokens = EstimateTokens(wholeFileToolTotalBytes);
        double preciseSavings = manualTotalBytes > 0 ? 1 - ((double)preciseToolTotalBytes / manualTotalBytes) : 0;
        double wholeFileSavings = manualTotalBytes > 0 ? 1 - ((double)wholeFileToolTotalBytes / manualTotalBytes) : 0;

        StringBuilder builder = new();
        builder.AppendLine("# Synthetic edit workflow token benchmark");
        builder.AppendLine();
        builder.AppendLine($"source duplicated: `{sourcePath}`");
        builder.AppendLine($"synthetic file: `{syntheticPath}`");
        builder.AppendLine($"edit steps: {rows.Count.ToString(CultureInfo.InvariantCulture)}");
        builder.AppendLine();
        builder.AppendLine("## Totals");
        builder.AppendLine($"manual full-file context: {manualTokens:N0} token-proxy ({manualTotalBytes:N0} bytes)");
        builder.AppendLine($"precise MCP-style edits: {preciseTokens:N0} token-proxy ({preciseToolTotalBytes:N0} bytes)");
        builder.AppendLine($"whole-file submit_file edits: {wholeFileTokens:N0} token-proxy ({wholeFileToolTotalBytes:N0} bytes)");
        builder.AppendLine();
        builder.AppendLine("## Ratios");
        builder.AppendLine($"precise-tool savings vs manual: {preciseSavings:P1}");
        builder.AppendLine($"whole-file-tool savings vs manual: {wholeFileSavings:P1}");
        builder.AppendLine($"manual / precise-tool ratio: {(preciseToolTotalBytes > 0 ? (double)manualTotalBytes / preciseToolTotalBytes : 0):F2}x");
        builder.AppendLine($"whole-file / precise-tool ratio: {(preciseToolTotalBytes > 0 ? (double)wholeFileToolTotalBytes / preciseToolTotalBytes : 0):F2}x");
        builder.AppendLine();
        builder.AppendLine("## Interpretation");
        builder.AppendLine("This isolates the edit-context cost of repeated full-file reads versus correctly scoped MCP text edits.");
        builder.AppendLine("It intentionally keeps a whole-file submit_file arm to catch the failure mode where an agent uses MCP but still sends large payloads.");
        return builder.ToString();
    }

    private static string ResolveRepositoryRoot()
    {
        string? configured = Environment.GetEnvironmentVariable("CODING_SERVICES_REPO_ROOT");
        if (!string.IsNullOrWhiteSpace(configured))
        {
            return Path.GetFullPath(configured);
        }

        DirectoryInfo? current = new(AppContext.BaseDirectory);
        while (current is not null)
        {
            if (File.Exists(Path.Combine(current.FullName, "AICodingServices.slnx")))
            {
                return current.FullName;
            }

            current = current.Parent;
        }

        return Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", ".."));
    }

    private static long CountUtf8(string value)
    {
        return Encoding.UTF8.GetByteCount(value);
    }

    private static double EstimateTokens(long bytes)
    {
        return bytes / 4.0;
    }

    private static string EscapeCsv(string value)
    {
        return "\"" + value.Replace("\"", "\"\"", StringComparison.Ordinal) + "\"";
    }

    private sealed record SyntheticEdit(string Name, string OldText, string NewText);

    private sealed record MeasurementRow(
        int Step,
        string Name,
        long ManualFullReadBytes,
        long PreciseToolPayloadBytes,
        long WholeFileToolPayloadBytes,
        long CumulativeManualBytes,
        long CumulativePreciseToolBytes,
        long CumulativeWholeFileToolBytes);
}
